name: Release
on:
  workflow_dispatch: # Manual trigger
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    container:
      image: eclipse-temurin:17
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - run: sed -i 's/obfuscated = false/obfuscated = true/' build.gradle
      - run: sed -i 's/debugInformation = true/debugInformation = false/' build.gradle
      - run: ./gradlew build -x test --stacktrace
      - run: mv resources/index.html build/generated/teavm
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/generated/teavm'
      - id: deployment
        uses: actions/deploy-pages@v4
